defaults:
  - model: baseline
  - metrics: example
  - datasets: asvspoof_eval # we do not want to run inference on training data
  - dataloader: example
  - transforms: example
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "predictions.csv" # any name here, can be a dataset name
  seed: 42
  from_pretrained: "saved/lcnn_baseline/checkpoint-epoch21-53298.pth"  # path to the pretrained model
